// File generated by FlutterFire CLI / Aura Configuration.
// Project: aurajewelry-2d68d (AuraJewelry)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// Configured for project: aurajewelry-2d68d
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuraJewelryWebKey2026_Placeholder',
    appId: '1:1029384756:web:aurajewelryweb123',
    messagingSenderId: '1029384756',
    projectId: 'aurajewelry-2d68d',
    authDomain: 'aurajewelry-2d68d.firebaseapp.com',
    storageBucket: 'aurajewelry-2d68d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuraJewelryAndroidKey2026_Placeholder',
    appId: '1:1029384756:android:aurajewelryapp123',
    messagingSenderId: '1029384756',
    projectId: 'aurajewelry-2d68d',
    storageBucket: 'aurajewelry-2d68d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuraJewelryIOSKey2026_Placeholder',
    appId: '1:1029384756:ios:aurajewelryios123',
    messagingSenderId: '1029384756',
    projectId: 'aurajewelry-2d68d',
    storageBucket: 'aurajewelry-2d68d.firebasestorage.app',
    iosBundleId: 'com.aura.luxury.jewelry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuraJewelryIOSKey2026_Placeholder',
    appId: '1:1029384756:ios:aurajewelryios123',
    messagingSenderId: '1029384756',
    projectId: 'aurajewelry-2d68d',
    storageBucket: 'aurajewelry-2d68d.firebasestorage.app',
    iosBundleId: 'com.aura.luxury.jewelry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuraJewelryWebKey2026_Placeholder',
    appId: '1:1029384756:web:aurajewelryweb123',
    messagingSenderId: '1029384756',
    projectId: 'aurajewelry-2d68d',
    authDomain: 'aurajewelry-2d68d.firebaseapp.com',
    storageBucket: 'aurajewelry-2d68d.firebasestorage.app',
  );
}
